on:
  issues:
    types: [created]
jobs:
  issueCreated:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.id }}
          reactions: eyes
