name: Test Action

on:
  issues:
    types: [created, opened]
#  - workflow_dispatch
    
jobs:
  issueCreated:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.id }}
          reactions: eyes
