name: Test Action

on:
  issue_comment:
    types: [created]
#  - workflow_dispatch
    
jobs:
  issueCommentCreated:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.comment.id }}
          reactions: eyes
